spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/recipe_service?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    username: "root"
    password:  "mintajzporem"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      cache:
        use_second_level_cache: true
      region:
        factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    show-sql: true
  application:
    name: TastyAppBackend



server:
  port: 8080
#  ssl:
#    key-store: src/main/resources/keystore.jks
#    key-store-password: password
#    enabled: true
#    key-password: password
app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000

page:
  size: 10
  default-page: 0