spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/recipe_service?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    username: "root"
    password:  "mintajzporem"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      cache:
        use_second_level_cache: true
      region:
        factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

  application:
    name: TastyAppBackend



server:
  port: 8080
