spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/db?verifyServerCertificate=false&useSSL=false&requireSSL=false"
    username: "user"
    password:  "user"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: update
      cache:
        use_second_level_cache: false
      region:
        factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

    show-sql: true
  application:
    name: TastyAppBackend
  mail:
    host: smtp.gmail.com
    port: 587
    username: "konrad.podgorski1999@gmail.com"
    password: "########"
    properties:
      mail:
        smtp:
          starttls:
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 15MB
server:
  port: 8080
#  ssl:
#    key-store: src/main/resources/keystore.jks
#    key-store-password: password
#    enabled: true
#    key-password: password
app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000
  domain: "http://localhost:8080"


page:
  size: 10
  default-page: 0

image:
  maxSize: 300

activity_tracker_config:
  artificial_session_id: "sessionId"

activity_tracker:
  sessionidheader: "sessionId"